development:
  adapter: postgresql
  encoding: unicode
  pool: 5 # Definida por padrão
  database: biblioteca_de_filmes 
  username: postgres
  password: postgres
  host: rails_postgres_1
  port: 5432