inherit_from: .rubocop_todo.yml

inherit_from:
  - .rubocop_todo.yml
require:
  - rubocop-rails
AllCops:
  NewCops: enable # Habilita novas regras por padrão
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
Rails:
  Enabled: true